unsupported C++ header: xlocal
Apple's API xlocal for extended locale support is not ported to
other major plattforms than Windows, iOS/OSX or BSD/FreeBSD 9.1.
On the other hand there is no code in the implementation class
of LibUSB::Configuration that will use this API.

So we remove the include directive.

Error was:

.../src/configuration_impl.cpp:23:19: fatal error:
   xlocale: No such file or directory

Signed-off-by: Stephan Linz <linz@li-pro.net>