add missing public statement in transfer interface
Error was:

.../src/endpoint_impl.cpp:130:109:   required from here
/usr/include/c++/4.8/bits/shared_ptr_base.h:963:64: error:
   ‘std::enable_shared_from_this<LibUSB::Transfer>’ is an
   inaccessible base of ‘LibUSB::ControlTransfer’

.../src/endpoint_impl.cpp:144:111:   required from here
/usr/include/c++/4.8/bits/shared_ptr_base.h:963:64: error:
   ‘std::enable_shared_from_this<LibUSB::Transfer>’ is an
   inaccessible base of ‘LibUSB::InterruptTransfer’

.../src/endpoint_impl.cpp:157:106:   required from here
/usr/include/c++/4.8/bits/shared_ptr_base.h:963:64: error:
   ‘std::enable_shared_from_this<LibUSB::Transfer>’ is an
   inaccessible base of ‘LibUSB::BulkTransfer’

.../src/endpoint_impl.cpp:168:113:   required from here
/usr/include/c++/4.8/bits/shared_ptr_base.h:963:64: error:
   ‘std::enable_shared_from_this<LibUSB::Transfer>’ is an
   inaccessible base of ‘LibUSB::IsochronousTransfer’

Signed-off-by: Stephan Linz <linz@li-pro.net>